juejin:
  cookie: ${juejin_cookie}

youdao:
  cookie: ${youdao_cookie}

weixin:
  corpId: ${weixin_corpId}
  agentId: ${weixin_agentId}
  corpsecret: ${weixin_corpsecret}
  token: ${weixin_token}
  encodingAESKey: ${weixin_encodingAESKey}

dingtalk:
  appKey: ${dingtalk_appKey}
  appSecret: ${dingtalk_appSecret}

chatgpt:
  openai:
    authorization: ${chatgpt_authorization}

pudn:
  authorization: ${pudn_authorization}
