

juejin:
  cookie: ${juejin_cookie}

youdao:
  cookie: ${youdao_cookie}

weixin:
  corpId: ${weixin_corpId}
  agentId: ${weixin_agentId}
  corpsecret: ${weixin_corpsecret}

dingtalk:
  accessToken: ${dingtalk_accessToken}
  secret: ${dingtalk_secret}
