version: '3.0'

services:
  automatic:
    container_name: automatic
    image: registry.cn-hangzhou.aliyuncs.com/4c6565/automatic
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - ./logs:/work/logs
    environment:
      - JAVA_OPTS=-Xms300m -Xmx400m
      - juejin_cookie=// 浏览器抓包看下cookie
      #- youdao_cookie=// 浏览器抓包看下cookie  暂时取消
      - pudn_authorization=// 浏览器抓包看下cookie
      - weixin_corpId=// 企业ID
      - weixin_agentId=// 应用ID
      - weixin_corpsecret=// 应用Secret
      - weixin_token=// 应用配置接收API设置的Token
      - weixin_encodingAESKey=// 应用配置接收API设置的EncodingAESKey
      - dingtalk_appKey=// 钉钉应用的appkey
      - dingtalk_appSecret=// 钉钉应用的appSecret
      - chatgpt_authorization=// chatGPT中生成的authorization