name: Maven Package And Docker Push And Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'liberica'

      - name: Build with Maven
        run: mvn -U package -Dmaven.test.skip=true --file pom.xml

      - name: Docker Build And Push to Aliyun
        run: |
          docker login --username=4c6565 registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }}
          docker build -t automatic . -f docker/Dockerfile 
          docker tag automatic ${{ vars.IMAGE_NAME }}:latest
          docker push ${{ vars.IMAGE_NAME }}:latest

#      - name: Deploy to Server
#        uses: cross-the-world/ssh-pipeline@master
#        with:
#          host: ${{ secrets.HOST }}
#          user: root
#          pass: ${{ secrets.PASS }}
#          script: |
#            cd ${{ vars.WORK }}
#            docker pull ${{ vars.IMAGE_NAME }}
#            docker-compose up -d
#            docker rmi `docker images | grep ${{ vars.IMAGE_NAME }} | grep none | awk '{print $3}'`