name: Maven Package And Docker Push

on:
  push:
    branches:
      - 'master'

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'liberica'

      - name: Build with Maven
        run: mvn -U package -Dmaven.test.skip=true --file pom.xml

      - name: Docker Build And Push to Aliyun
        run: |
          docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }}
          docker build -t automatic . -f docker/Dockerfile 
          docker tag automatic registry.cn-hangzhou.aliyuncs.com/4c6565/automatic:latest
          docker push registry.cn-hangzhou.aliyuncs.com/4c6565/automatic:latest